#!/usr/bin/env python3
"""Push generated archive to HuggingFace as EvanOLeary/pallasbench-t4-archive."""
import os, sys, argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

def push(results_dir: str, repo_id: str, token: str):
    from huggingface_hub import HfApi, DatasetCard
    import pandas as pd

    api = HfApi(token=token)
    results = Path(results_dir)

    # Create repo if needed
    try:
        api.create_repo(repo_id=repo_id, repo_type="dataset", exist_ok=True)
        print(f"Repo: https://huggingface.co/datasets/{repo_id}")
    except Exception as e:
        print(f"Repo create warning: {e}")

    # Upload parquet files
    for parquet in sorted(results.glob("level_*.parquet")):
        split = parquet.stem  # e.g. level_1
        df = pd.read_parquet(parquet)
        print(f"  {split}: {len(df)} rows, {len(df.columns)} cols")
        api.upload_file(
            path_or_fileobj=str(parquet),
            path_in_repo=f"data/{parquet.name}",
            repo_id=repo_id,
            repo_type="dataset",
        )

    # Upload dataset card
    card_content = f"""---
license: apache-2.0
task_categories:
- text-generation
language:
- code
tags:
- jax
- pallas
- gpu-kernels
- benchmark
- pallasbench
---

# PallasBench T4 Archive

JAX/Pallas kernel benchmark dataset — SakanaAI AI-CUDA-Engineer-Archive format, targeting **NVIDIA T4 (sm_75)** GPU.

Companion to [EvanOLeary/pallasbench-robust-gpu-a100](https://huggingface.co/datasets/EvanOLeary/pallasbench-robust-gpu-a100) (A100 results).

## Schema

Extends SakanaAI's 19-column schema with JAX-native IR:

| Column | Type | Description |
|--------|------|-------------|
| `Op_Name` | str | Operation name |
| `Level_ID` | int | Difficulty (1/2/3) |
| `Task_ID` | int | Task identifier |
| `LLM_Model` | str | `seed` or Azure model name |
| `Generation_Idx` | int | 0=seed, 1..n=LLM variants |
| `Pallas_Code` | str | Generated Pallas kernel |
| `JAX_Code_Functional` | str | JAX reference implementation |
| `Correct` | bool | Passes correctness check |
| `Max_Diff` | float | Max numerical diff from reference |
| `JAX_Native_Runtime` | float | JAX eager GPU timing (ms) |
| `JAX_XLA_Compiled_Runtime` | float | jit-compiled timing (ms) |
| `Jaxpr_IR` | str | Shape-annotated Jaxpr compute graph |
| `StableHLO_IR` | str | StableHLO MLIR text |
| `fast_0/1/2/5` | bool | Correct + speedup thresholds |

## Generation

Archive generated by `DeepSeek-V3-2` via Azure OpenAI, 20 variants per problem,
with error-feedback loop (up to 2 retries per variant).

## Hardware

T4 (sm_75): Pallas interpret=True for correctness; JAX reference timings on GPU.
For native Pallas perf, see the A100 dataset.
"""
    card_path = results / "README.md"
    card_path.write_text(card_content)
    api.upload_file(
        path_or_fileobj=str(card_path),
        path_in_repo="README.md",
        repo_id=repo_id,
        repo_type="dataset",
    )
    print(f"\n✓ Uploaded to https://huggingface.co/datasets/{repo_id}")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("results_dir")
    p.add_argument("--repo", default="EvanOLeary/pallasbench-t4-archive")
    p.add_argument("--token", default=os.environ.get("HF_TOKEN", ""))
    args = p.parse_args()
    push(args.results_dir, args.repo, args.token)
